Skip 2 levels instead of 1 while evaluating nonSloggerCaller
mongodb/slogger pull request #20
Opened 2022-10-31 21:30 UTC by ramasai1

Skipping one level would put us in the stack frame for `logf(...)`, which is an internal function and can be skipped over too. 

QA: Ran tests and they were good.

cc @dunkyboy @alex-dambrouski

2022-10-31 21:40 UTC, tolsen requested changes
Please add a comment that this function must remain private so that we can start at skip level 2 :-)

Also, I would remove an explicit reference to logf() in the current comment.  Just say that keeping this function private means that we know we can skip this function and whatever function in this package that calls it.

2022-11-01 12:15 UTC, ramasai1 commented
@tolsen this is ready for another look.

2022-11-01 13:45 UTC, tolsen approved these changes
perfect comment :-)

2022-11-01 15:02 UTC, ramasai1 commented
@tolsen could you please merge this 😅

2022-11-01 15:21 UTC, merged